### PR TITLE
Fix so that library compiles under Ubuntu (17.04)

### PR DESCRIPTION
**Pull request by multivac61**
I was unable to compile the library under Ubuntu. One part was explained in #21 which can now be closed.

The changes in this PR, which added linker flags and some include statements, allowed me to successfully build it.

### CODE REVIEW

**Comment by zedshaw** [comment]
Great, thanks for figuring this out.  I'll have to test it on a few more platforms to confirm it doesn't break anything.

**Comment by multivac61** [comment]
My pleasure. Let me know if I can be of any further assistance.

**Comment by MarcMcIntosh** [comment]
This also happens under other linux distros.

So much time wasted trying to write mergesort, when I could have just added -lbsd to make file

**Comment by Bscout2011** [comment]
Additionally, I had to install the bsd library on my system.
`sudo apt install libbsd-dev`

**Pull request merged**
